### ISSUE TITLE
java.net.UnknownHostException using docker-compose

### ISSUE THREAD

**Issue by mzbyszynski** [31z4/storm-docker#1]
Hi there!

Thanks you for creating this project! It was just what I was looking for to test upgrading to storm 1.0.1.

I've copied your docker-compose configuration and it seems to be running, but I am not able to connect to it from outside docker, even though the 6627 port is exposed. I'm running on Ubuntu with the latest docker-engine and docker-compose versions, and when I try a simple `storm list` command, I get the below exception. Have you seen this before? Any idea what I am doing wrong?

Thanks for your help!
-Marc

```
$ which storm
/home/mzbyszynski/Applications/apache-storm-1.0.1/bin/storm
$ docker-compose -f src/docker/docker-compose.yml ps
       Name                      Command               State           Ports          
-------------------------------------------------------------------------------------
docker_nimbus_1       storm nimbus -c storm.zook ...   Up      0.0.0.0:6627->6627/tcp 
docker_supervisor_1   storm supervisor -c storm. ...   Up                             
docker_zookeeper_1    /docker-entrypoint.sh zkSe ...   Up      2181/tcp               
$ storm remoteconfvalue nimbus.seeds
nimbus.seeds: [localhost]
$ storm remoteconfvalue nimbus.thrift.port
nimbus.thrift.port: 6627
$ storm localconfvalue nimbus.thrift.port
nimbus.thrift.port: 6627
t$ storm localconfvalue nimbus.seeds
nimbus.seeds: [localhost]
$ storm list
Running: /usr/lib/jvm/java-8-oracle/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/home/mzbyszynski/Applications/apache-storm-1.0.1 -Dstorm.log.dir=/home/mzbyszynski/Applications/apache-storm-1.0.1/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /home/mzbyszynski/Applications/apache-storm-1.0.1/lib/reflectasm-1.10.1.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/clojure-1.7.0.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/minlog-1.3.0.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/disruptor-3.3.2.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/asm-5.0.3.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/servlet-api-2.5.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/storm-rename-hack-1.0.1.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/log4j-api-2.1.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/log4j-over-slf4j-1.6.6.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/kryo-3.0.3.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/objenesis-2.1.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/storm-core-1.0.1.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/log4j-core-2.1.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/lib/slf4j-api-1.7.7.jar:/home/mzbyszynski/Applications/apache-storm-1.0.1/conf:/home/mzbyszynski/Applications/apache-storm-1.0.1/bin org.apache.storm.command.list
Exception in thread "main" java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException: java.net.UnknownHostException: 28cb4180e92a
    at org.apache.storm.security.auth.TBackoffConnect.retryNext(TBackoffConnect.java:64)
    at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:56)
    at org.apache.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:99)
    at org.apache.storm.security.auth.ThriftClient.<init>(ThriftClient.java:69)
    at org.apache.storm.utils.NimbusClient.<init>(NimbusClient.java:106)
    at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:78)
    at org.apache.storm.command.list$_main.invoke(list.clj:22)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at org.apache.storm.command.list.main(Unknown Source)
Caused by: org.apache.storm.thrift.transport.TTransportException: java.net.UnknownHostException: 28cb4180e92a
    at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:226)
    at org.apache.storm.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
    at org.apache.storm.security.auth.SimpleTransportPlugin.connect(SimpleTransportPlugin.java:103)
    at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:53)
    ... 8 more
Caused by: java.net.UnknownHostException: 28cb4180e92a
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:221)
    ... 11 more
```

**Comment by tomvanduist** [comment]
I encountered the same problem, for me the problem was that the host could not be resolved.
I.e its a DNS error where the client doesnt know with which IP to connect, it cant resolve host _28cb4180e92a_ to an address.

I resolved it by explicitly naming each client as their IP through the _storm.local.hostname_ option.
Not the most elegant solution but if anything it helps you pinpoint the problem.

**Comment by 31z4** [comment]
@mzbyszynski Thanks for your report!

@tomvanduist is right. Seems like [storm.local.hostname](https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/Config.java#L259-L268) should be used to fix DNS issues inside the containers.

This docker compose works for me

``` yaml
version: '2'
services:
    zookeeper:
        image: 31z4/zookeeper:3.4.8
        restart: always

    nimbus:
        image: 31z4/storm:1.0.1
        command: >
            storm nimbus
            -c storm.zookeeper.servers="[\"zookeeper\"]"
            -c nimbus.host="nimbus"
            -c storm.local.hostname=localhost
        depends_on:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    supervisor:
        image: 31z4/storm:1.0.1
        command: >
            storm supervisor
            -c storm.zookeeper.servers="[\"zookeeper\"]"
            -c nimbus.seeds="[\"nimbus\"]"
            -c storm.local.hostname=supervisor
        depends_on:
            - nimbus
        restart: always
```

Please confirm that it works for you.

Another way is to use `storm` from within the running nimbus container

```
$ docker exec -it docker_nimbus_1 storm list
```

**Comment by mzbyszynski** [comment]
Adding `-c storm.local.hostname=localhost` to the nimbus host did the trick. Thanks you @tomvanduist and @31z4 !

**Comment by normansuesstrunk** [comment]
I've run into the same exact error and found this issue. 

OS: Ubuntu 16.06 LTS 

My docker-compose.yml with added host entries etc. (suggested in this issue) are as following :

```version: '2'
services:
    zookeeper:
        image: zookeeper:3.4
        container_name: zookeeper
        restart: always

    nimbus:
        image: storm:1.0.2
        container_name: nimbus
        command: >
            storm nimbus
            -c storm.zookeeper.servers="[\"zookeeper\"]"
            -c nimbus.host="nimbus"
            -c storm.local.hostname=localhost
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    supervisor:
        image: storm:1.0.2
        container_name: supervisor
        command: >
            storm supervisor
            -c storm.zookeeper.servers="[\"zookeeper\"]"
            -c nimbus.seeds="[\"nimbus\"]"
            -c storm.local.hostname=supervisor
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always
```

Trying to add a Topology (Stormcrawler) with the following command: 
```
docker run -it --rm -v $(pwd)/target/stormcrawler-0.0.1-SNAPSHOT.jar:/stormcrawler-0.0.1-SNAPSHOT.jar storm:1.0.2 storm jar /stormcrawler-0.0.1-SNAPSHOT.jar CrawlTopology
```

Error: 

```
Running: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/apache-storm-1.0.2 -Dstorm.log.dir=/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /apache-storm-1.0.2/lib/clojure-1.7.0.jar:/apache-storm-1.0.2/lib/kryo-3.0.3.jar:/apache-storm-1.0.2/lib/slf4j-api-1.7.7.jar:/apache-storm-1.0.2/lib/asm-5.0.3.jar:/apache-storm-1.0.2/lib/log4j-over-slf4j-1.6.6.jar:/apache-storm-1.0.2/lib/servlet-api-2.5.jar:/apache-storm-1.0.2/lib/log4j-api-2.1.jar:/apache-storm-1.0.2/lib/storm-core-1.0.2.jar:/apache-storm-1.0.2/lib/log4j-slf4j-impl-2.1.jar:/apache-storm-1.0.2/lib/log4j-core-2.1.jar:/apache-storm-1.0.2/lib/minlog-1.3.0.jar:/apache-storm-1.0.2/lib/storm-rename-hack-1.0.2.jar:/apache-storm-1.0.2/lib/disruptor-3.3.2.jar:/apache-storm-1.0.2/lib/objenesis-2.1.jar:/apache-storm-1.0.2/lib/reflectasm-1.10.1.jar:/stormcrawler-0.0.1-SNAPSHOT.jar:/conf:/apache-storm-1.0.2/bin -Dstorm.jar=/stormcrawler-0.0.1-SNAPSHOT.jar ch.htwchur.ds9.CrawlTopology
932  [main] INFO  o.a.s.StormSubmitter - Generated ZooKeeper secret payload for MD5-digest: -8546106236276736012:-7759757426464791389
1040 [main] INFO  o.a.s.s.a.AuthUtils - Got AutoCreds []
11341 [main] WARN  o.a.s.u.NimbusClient - Ignoring exception while trying to get leader nimbus info from nimbus. will retry with a different seed host.
java.lang.RuntimeException: org.apache.storm.thrift.transport.TTransportException: java.net.UnknownHostException: nimbus
	at org.apache.storm.security.auth.TBackoffConnect.retryNext(TBackoffConnect.java:64) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:56) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:99) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.security.auth.ThriftClient.<init>(ThriftClient.java:69) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.utils.NimbusClient.<init>(NimbusClient.java:106) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:66) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:371) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:311) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:157) [storm-core-1.0.2.jar:1.0.2]
	at com.digitalpebble.stormcrawler.ConfigurableTopology.submit(ConfigurableTopology.java:85) [stormcrawler-0.0.1-SNAPSHOT.jar:?]
	at ch.htwchur.ds9.CrawlTopology.run(CrawlTopology.java:72) [stormcrawler-0.0.1-SNAPSHOT.jar:?]
	at com.digitalpebble.stormcrawler.ConfigurableTopology.start(ConfigurableTopology.java:50) [stormcrawler-0.0.1-SNAPSHOT.jar:?]
	at ch.htwchur.ds9.CrawlTopology.main(CrawlTopology.java:38) [stormcrawler-0.0.1-SNAPSHOT.jar:?]
Caused by: org.apache.storm.thrift.transport.TTransportException: java.net.UnknownHostException: nimbus
	at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:226) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.transport.TFramedTransport.open(TFramedTransport.java:81) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.security.auth.SimpleTransportPlugin.connect(SimpleTransportPlugin.java:103) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:53) ~[storm-core-1.0.2.jar:1.0.2]
	... 12 more
Caused by: java.net.UnknownHostException: nimbus
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_111-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_111-internal]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_111-internal]
	at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:221) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.transport.TFramedTransport.open(TFramedTransport.java:81) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.security.auth.SimpleTransportPlugin.connect(SimpleTransportPlugin.java:103) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:53) ~[storm-core-1.0.2.jar:1.0.2]
	... 12 more
org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [nimbus]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:90)
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:371)
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:311)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:157)
	at com.digitalpebble.stormcrawler.ConfigurableTopology.submit(ConfigurableTopology.java:85)
	at ch.htwchur.ds9.CrawlTopology.run(CrawlTopology.java:72)
	at com.digitalpebble.stormcrawler.ConfigurableTopology.start(ConfigurableTopology.java:50)
	at ch.htwchur.ds9.CrawlTopology.main(CrawlTopology.java:38)
```

any ideas? many thanks!

**Comment by summerisgone** [comment]
@normansuesstrunk we have exact same issue, cleaning `/storm` path in zookeeper helps as workaround.

**Comment by aykutyararbas** [comment]
This solution does not work on a docker swarm with multiple hosts:

2019-05-26 20:15:32.879 o.a.s.s.o.a.z.ZooKeeper main [INFO] Initiating client connection, connectString=zookeeper:2181 sessionTimeout=20000 watcher=org.apache.storm.shade.org.apache.curator.ConnectionState@7c369270
2019-05-26 20:15:32.879 o.a.s.s.o.a.c.f.i.CuratorFrameworkImpl main [ERROR] Background exception was not retry-able or retry gave up
java.net.UnknownHostException: zookeeper
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_212]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_212]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_212]
	at org.apache.storm.shade.org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61) ~[storm-core-1.2.2.jar:1.2.2]
	at org.apache.storm.shade.org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) ~[storm-core-1.2.2.jar:1.2.2]



here is my stack yml
version: '3.1'
services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always

    nimbus:
        image: storm
        container_name: nimbus
        command: >
            storm nimbus
            -c storm.zookeeper.servers="[\"zookeeper\"]"
            -c nimbus.host="nimbus"
            -c storm.local.hostname=localhost
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627
