### ISSUE TITLE
Storm UI not working with Older versions (0.9 and 0.10)

### ISSUE THREAD

**Issue by koldkoder** [31z4/storm-docker#9]
I tried bringing up a minimal docker cluster, using following command

List of Commands 
docker run -d --restart always --name some-zookeeper zookeeper:3.4

- docker run -d --restart always --name some-nimbus --link some-zookeeper:zookeeper storm:0.10 storm nimbus
- docker run -d --restart always --name supervisor --link some-zookeeper:zookeeper --link some-nimbus:nimbus storm:0.10 storm supervisor
- docker run -d --restart always --name supervisor --link some-zookeeper:zookeeper --link some-nimbus:nimbus storm:0.10 storm supervisor
- docker run -d -p 8080:8080 --restart always --name ui --link some-nimbus:nimbus storm:0.10 storm ui

When you go to http://localhst:8080/index.html,  i am being greeted with a InternalServerError

```
Internal Server Error
java.lang.RuntimeException: org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at backtype.storm.security.auth.TBackoffConnect.retryNext(TBackoffConnect.java:59)
	at backtype.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:51)
	at backtype.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:103)
	at backtype.storm.security.auth.ThriftClient.<init>(ThriftClient.java:72)
	at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:69)
	at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:76)
	at backtype.storm.ui.core$supervisor_summary.invoke(core.clj:578)
	at backtype.storm.ui.core$fn__9652.invoke(core.clj:967)
	at org.apache.storm.shade.compojure.core$make_route$fn__1829.invoke(core.clj:93)
	at org.apache.storm.shade.compojure.core$if_route$fn__1817.invoke(core.clj:39)
	at org.apache.storm.shade.compojure.core$if_method$fn__1810.invoke(core.clj:24)
	at org.apache.storm.shade.compojure.core$routing$fn__1835.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2515)
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:626)
	at org.apache.storm.shade.compojure.core$routes$fn__1839.invoke(core.clj:111)
	at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__8930.invoke(json.clj:56)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__2889.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__3620.invoke(reload.clj:22)
	at backtype.storm.ui.core$catch_errors$fn__9723.invoke(core.clj:1061)
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__2822.invoke(keyword_params.clj:27)
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__2861.invoke(nested_params.clj:65)
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__2794.invoke(params.clj:55)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__2889.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__3070.invoke(flash.clj:14)
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__3059.invoke(session.clj:43)
	at org.apache.storm.shade.ring.middleware.cookies$wrap_cookies$fn__2990.invoke(cookies.clj:160)
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__2707.invoke(servlet.clj:127)
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__2711.invoke(servlet.clj:136)
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at backtype.storm.ui.helpers$x_frame_options_filter_handler$fn__3205.invoke(helpers.clj:191)
	at backtype.storm.ui.helpers.proxy$java.lang.Object$Filter$abec9a8f.doFilter(Unknown Source)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift7.transport.TSocket.open(TSocket.java:187)
	at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)
	at backtype.storm.security.auth.SimpleTransportPlugin.connect(SimpleTransportPlugin.java:103)
	at backtype.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:48)
	... 61 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift7.transport.TSocket.open(TSocket.java:182)
	... 64 more


```

Everything works as expected with storm 1.0.2

**Comment by madisonb** [comment]
For anyone who stumbles upon this. You appear to be able to pass the nimbus host as a command line argument

```
storm ui -c nimbus.host=nimbus
```

Which will allow you to override the default `localhost` variable.

**Comment by 31z4** [comment]
Thanks for reporting this @koldkoder! Should be fixed now.

**Comment by sbilello** [comment]
https://github.com/sbilello/coincident-hashtags-with-apache-storm
If you run
`docker-compose up`
ssh to `nimbus` container
`docker exec -it nimbus bash `
and then run
`storm ui` or `storm ui -c nimbus.host=nimbus`
You will get the following broken UI
@madisonb 
<img width="865" alt="screen shot 2018-07-10 at 7 26 26 pm" src="https://user-images.githubusercontent.com/1815376/42547464-2bb298bc-8477-11e8-8d4a-83f3b7574b89.png">
